name: Rebuild LLVM Toolchain

on:
  workflow_dispatch:
jobs:
  build-llvm:
    name: Build LLVM Toolchain
    runs-on: ubuntu-24.04-arm

    steps:
    # 1. Checkout kode repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. Install dependencies
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git \
          cmake \
          ninja-build \
          clang \
          python3 \
          make \
          unzip \
          wget \
          repo

    # 3. Download Android NDK r14b
    - name: Download Android NDK r14b
      run: |
        mkdir -p $GITHUB_WORKSPACE/android-ndk-r14b
    # 4. Setup build environment
    - name: Setup Build Environment
      run: |
        mkdir -p $GITHUB_WORKSPACE/llvm-toolchain
        cd $GITHUB_WORKSPACE/llvm-toolchain
        repo init -u https://android.googlesource.com/platform/manifest -b master
        repo sync -c -j$(nproc)

    # 5. Configure and build LLVM
    - name: Configure and Build LLVM
      run: |
        cd $GITHUB_WORKSPACE/llvm-toolchain
        # Set up environment variables as needed
        export NDK=$GITHUB_WORKSPACE/android-ndk-r14b
        export TOOLCHAIN=$NDK/toolchains/llvm/prebuilt/linux-x86_64
        export TARGET=aarch64-linux-android
        export API=21
        export AR=$TOOLCHAIN/bin/$TARGET-ar
        export AS=$TOOLCHAIN/bin/$TARGET-as
        export CC=$TOOLCHAIN/bin/$TARGET$API-clang
        export CXX=$TOOLCHAIN/bin/$TARGET$API-clang++
        export LD=$TOOLCHAIN/bin/$TARGET-ld
        export STRIP=$TOOLCHAIN/bin/$TARGET-strip
        # Configure and build
        mkdir build
        cd build
        cmake -G Ninja \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/llvm-install \
          ..
        ninja
        ninja install

    # 6. Upload hasil build sebagai artifact
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: llvm-toolchain
        path: $GITHUB_WORKSPACE/llvm-install/
